name: Scrape New CodeWars Solved Katas

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 */2 * *" # 12:00 AM IST

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            lsof \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libnss3 \
            libcups2 \
            libxrandr2 \
            libasound2 \
            libpangocairo-1.0-0 \
            libpango-1.0-0 \
            libcairo2 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libgbm1 \
            libxshmfence1 \
            libegl1 \
            libxkbcommon0 \
            libdbus-1-3

      - name: Install Google Chrome
        run: npx @puppeteer/browsers install chrome@stable

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "v22.5.1"

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        env:
          CODEWARS_USERNAME: ${{ secrets.CODEWARS_USERNAME }}
          CODEWARS_EMAIL: ${{ secrets.CODEWARS_EMAIL }}
          CODEWARS_PASSWORD: ${{ secrets.CODEWARS_PASSWORD }}
        run: node index.js

      - name: Set Today's Date
        run: echo "TODAY=$(date +'%Y/%m/%d')" >> "$GITHUB_ENV"

      - name: Increase Git buffer size
        run: git config http.postBuffer 524288000 # 500MB

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "Add katas solved on ${{ env.TODAY }}"
          add: .
